server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/a-shop
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:29092

kafka:
  topics:
      new_orders: new_orders
      payed_orders: payed_orders